/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Passport, PassportInterface } from "../Passport";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220c78265cb368a968231dfac8ece2bbdf82985a6ed8193f3e3d821b209d18bf5e564736f6c63430008040033";

export class Passport__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Passport> {
    return super.deploy(overrides || {}) as Promise<Passport>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Passport {
    return super.attach(address) as Passport;
  }
  connect(signer: Signer): Passport__factory {
    return super.connect(signer) as Passport__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PassportInterface {
    return new utils.Interface(_abi) as PassportInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Passport {
    return new Contract(address, _abi, signerOrProvider) as Passport;
  }
}
