/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "FactoryFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FactoryFactory__factory>;
    getContractFactory(
      name: "Passport",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Passport__factory>;
    getContractFactory(
      name: "PassportFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PassportFactory__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "FactoryFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FactoryFactory>;
    getContractAt(
      name: "Passport",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Passport>;
    getContractAt(
      name: "PassportFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PassportFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
