name: Publish Contracts
on:
  push:
    branches: main
    paths:
      - "packages/contracts/package.json"
      - ".github/workflows/contracts.yaml"

env:
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: install
        run: npm install
        working-directory: packages/contracts
      - name: build
        run: npm run build
        working-directory: packages/contracts
      - name: test
        run: npm run test
        working-directory: packages/contracts
      - name: Deploy to Kovan
        run: npm run migrate:kovan
        working-directory: packages/contracts
      - name: Deploy to Ropsten
        run: npm run migrate:ropsten
        working-directory: packages/contracts
      - name: Deploy to Rinkeby
        run: npm run migrate:rinkeby
        working-directory: packages/contracts
      - name: Deploy to Goerli
        run: npm run migrate:goerli
        working-directory: packages/contracts
      - name: Deploy to Firebase
        run: npm run deploy
        working-directory: packages/contracts
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          check-version: false
          package: ./packages/contracts/package.json
